# This rule is not used by the project model-validation-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ml.sigstore.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: model-validation-operator
    app.kubernetes.io/managed-by: kustomize
  name: modelvalidation-admin-role
rules:
- apiGroups:
  - ml.sigstore.dev
  resources:
  - modelvalidations
  verbs:
  - '*'
- apiGroups:
  - ml.sigstore.dev
  resources:
  - modelvalidations/status
  verbs:
  - get
